'type: developer':
  - .github/**
  - .husky/**
  - bin/**
  - .prettierrc
  - commitlint.config.js
  - package.json

'type: changelog':
  - changelog/**

'type:-dependencies':
  - package.json
  - yarn.lock
