blank_issues_enabled: false
contact_links:
  - name: Scaleway Documenation Issues
    url: https://github.com/scaleway/docs-content/issues
    about: Use one of the template options to create an issue