name: Documentation Bug
description: Open a new issue to help us improve Scaleway documentation.
title: "[🐞 Documentation Bug]: "
labels: "Documentation Bug"
body:
  - type: input
    attributes:
      label: Link to the documentation page or resource
      placeholder: https://www.scaleway.com/en/docs/
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug
      placeholder: "A clear and concise description of what the bug is"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      placeholder: "Add any other context about the problem"
    validations:
      required: false
  - type: textarea
    attributes:
      label: Related issue(s)/PR(s)
      placeholder: "Let us know if this is related to any issue/pull request"
    validations:
      required: false