name: Documentation Request
description: Suggest a topic or new documentation you think we should add!
title: "[👩‍💻 Documentation Request]: "
labels: "Documentation Request"
body:
  - type: textarea
    attributes:
      label: Summary
      placeholder: Quick summary of what is this documentation request about.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why is it needed?
      placeholder: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggested solution(s)
      placeholder: "A clear and concise description of what you want to happen."
    validations:
      required: false
  - type: textarea
    attributes:
      label: Related issue(s)/PR(s)
      placeholder: "Let us know if this is related to any issue/pull request."
    validations:
      required: false
  - type: textarea
    attributes:
      label: Scaleway Organisation ID
      placeholder: "To benefit from a discount on your Scaleway invoice, add your Organization ID here."
    validations:
      required: false
  - type: textarea
    attributes:
      label: Email address
      placeholder: "Leave us your email address in case we need to contact you."
    validations:
      required: false