extends: substitution
message: "'%s' should probably be '%s'"
link: https://docs.google.com/document/d/1Bjqn9xWktUek3_Ji72jj1Hfpuan48JpN4cMUnNJiELc/edit
level: error
ignorecase: false
action:
  name: replace
swap:
  My Test: my test
  Availability Zone: availability zone
  secret key: Secret Key
  access key:  Access Key
  API key: API Key
  Organization: organization
  Project: project
  Scaleway console: Scaleway Console
  Instance: instance
  volume: Volume
  image: Image
  snapshot: Snapshot