extends: ?
message: "Use '%s' instead of '%s'."
link: 
level: warning

# suggest replacing closely-matching but not-quite requirement strings with the preferred requirement string eg "You have an account and are logged into the Scaleway console"
