#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

RED='\033[0;31m'

[[ $(bin/count-invalid-slugs) == "0" ]] && \
yarn lint-staged || \
(echo "💔 \033[0;31mSlugs error(s): \033[0;36m" && bin/list-invalid-slugs \ 
echo "⚠️ \033[0;31mYou must fix slugs in 'menu/navigation.json' before commit!\033[0;0m"; exit 1)
